- hosts: server
  tasks:
    - name: Comment DR IP to etc hosts
      lineinfile:
        path: "/etc/hosts"
        regexp: "^10.200.1.202"
        replace: "#\1"
        state: present
        backup: yes