- hosts: fortilab
  collections:
    - fortinet.fortios
  connection: httpapi
  roles:
    - role: ansible-example-fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80
  tasks:
  - name: Configure interfaces.
    fortios_system_interface:
      vdom:  "{{ vdom }}"
      state: "present"
      system_interface:
        interface: "port2"
        ip: "10.1.1.1"
